defmodule MineSweeperWorld.Repo.Migrations.AddTimeLimitToGames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add :time_limit_seconds, :bigint
    end
  end

  def down do
    alter table(:games) do
      remove :time_limit_seconds
    end
  end
end
