defmodule MineSweeperWorld.Repo.Migrations.CreateGamesResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:games, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subdivisions, :bigint, null: false, default: 4
      add :mine_count, :bigint, null: false
      add :seed, :bigint, null: false
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "setup"
    end

    create table(:game_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :game_id,
          references(:games,
            column: :id,
            name: "game_memberships_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "game_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:game_memberships, [:game_id, :user_id],
             name: "game_memberships_unique_membership_index"
           )

    create table(:cells, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :index, :bigint, null: false
      add :kind, :text, null: false, default: "hexagon"
      add :mine?, :boolean, null: false, default: false
      add :adjacent_mine_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "hidden"

      add :game_id,
          references(:games,
            column: :id,
            name: "cells_game_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:cells, [:game_id, :index], name: "cells_unique_cell_index_index")

    create table(:cell_adjacencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :cell_id,
          references(:cells,
            column: :id,
            name: "cell_adjacencies_cell_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :neighbor_id,
          references(:cells,
            column: :id,
            name: "cell_adjacencies_neighbor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:cell_adjacencies, [:cell_id, :neighbor_id],
             name: "cell_adjacencies_unique_edge_index"
           )
  end

  def down do
    drop constraint(:cell_adjacencies, "cell_adjacencies_cell_id_fkey")

    drop constraint(:cell_adjacencies, "cell_adjacencies_neighbor_id_fkey")

    drop_if_exists unique_index(:cell_adjacencies, [:cell_id, :neighbor_id],
                     name: "cell_adjacencies_unique_edge_index"
                   )

    drop table(:cell_adjacencies)

    drop constraint(:cells, "cells_game_id_fkey")

    drop_if_exists unique_index(:cells, [:game_id, :index], name: "cells_unique_cell_index_index")

    drop table(:cells)

    drop constraint(:game_memberships, "game_memberships_game_id_fkey")

    drop constraint(:game_memberships, "game_memberships_user_id_fkey")

    drop_if_exists unique_index(:game_memberships, [:game_id, :user_id],
                     name: "game_memberships_unique_membership_index"
                   )

    drop table(:game_memberships)

    drop table(:games)
  end
end
